################################################################################
#
# gnuradio
#
################################################################################

GNURADIO_VERSION = 3.7.11
GNURADIO_SITE = http://gnuradio.org/releases/gnuradio
GNURADIO_LICENSE = GPL-3.0+
GNURADIO_LICENSE_FILES = COPYING

GNURADIO_SUPPORTS_IN_SOURCE_BUILD = NO

# host-python-cheetah is needed for volk to compile
GNURADIO_DEPENDENCIES = \
	host-python-cheetah \
	host-swig \
	boost

ifeq ($(BR2_PACKAGE_ORC),y)
GNURADIO_DEPENDENCIES += orc
endif

GNURADIO_CONF_OPTS = \
	-DENABLE_DEFAULT=OFF \
	-DENABLE_VOLK=ON \
	-DENABLE_GNURADIO_RUNTIME=ON

# For third-party blocks, the gnuradio libraries are mandatory at
# compile time.
GNURADIO_INSTALL_STAGING = YES

GNURADIO_CONF_OPTS += -DCMAKE_EXE_LINKER_FLAGS=-latomic
GNURADIO_CONF_OPTS += -DCMAKE_C_FLAGS="$(TARGET_CFLAGS) -march=armv7-a"
GNURADIO_CONF_OPTS += -DENABLE_GR_ANALOG=ON
GNURADIO_DEPENDENCIES += alsa-lib
GNURADIO_DEPENDENCIES += portaudio
GNURADIO_CONF_OPTS += -DENABLE_GR_AUDIO=ON
GNURADIO_CONF_OPTS += -DENABLE_GR_BLOCKS=ON
GNURADIO_CONF_OPTS += -DENABLE_GR_CHANNELS=ON

GNURADIO_CONF_OPTS += -DENABLE_GR_CTRLPORT=ON

GNURADIO_CONF_OPTS += -DENABLE_GR_DIGITAL=ON

GNURADIO_DEPENDENCIES += gsl
GNURADIO_CONF_OPTS += -DENABLE_GR_FEC=ON

GNURADIO_DEPENDENCIES += fftw
GNURADIO_CONF_OPTS += -DENABLE_GR_FFT=ON

GNURADIO_CONF_OPTS += -DENABLE_GR_FILTER=ON

GNURADIO_DEPENDENCIES += python
GNURADIO_CONF_OPTS += -DENABLE_PYTHON=ON

GNURADIO_CONF_OPTS += -DENABLE_PAGER=ON

#ifeq ($(BR2_PACKAGE_GNURADIO_QTGUI),y)
#GNURADIO_DEPENDENCIES += python-pyqt qwt
#GNURADIO_CONF_OPTS += -DENABLE_GR_QTGUI=ON
#else
GNURADIO_CONF_OPTS += -DENABLE_GR_QTGUI=OFF
#endif

GNURADIO_CONF_OPTS += -DENABLE_GR_TRELLIS=ON

GNURADIO_CONF_OPTS += -DENABLE_GR_UTILS=ON

$(eval $(cmake-package))
